include: package:flutter_lints/flutter.yaml

linter:
  rules:
    require_trailing_commas: true
    unawaited_futures: true
    always_use_package_imports: true
    avoid_dynamic_calls: true
    cancel_subscriptions: true
    close_sinks: true
    always_declare_return_types: true
    flutter_style_todos: true
    prefer_final_fields: true
    prefer_final_locals: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    super_goes_last: true
    unnecessary_lambdas: true
    use_enums: true
    use_super_parameters: true
    avoid_print: true
    prefer_single_quotes: true

analyzer:
  exclude: [
    build/**,
    "**/*.freezed.dart",
    "**/*.g.dart",
    l10n/**,
  ]

  errors:
    body_might_complete_normally_nullable: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options