name: askm
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  flutter: '3.19.2'
  sdk: '3.3.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # https://pub.dev/packages/dio
  dio: ^5.4.3+1
  # https://pub.dev/packages/get_it
  get_it: ^7.7.0
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.2.3
  # https://pub.dev/packages/flutter_native_splash
  flutter_native_splash: ^2.4.0
  # https://pub.dev/packages/auto_route
  auto_route: ^8.1.3
  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^8.1.6
  # https://pub.dev/packages/logger
  logger: ^2.3.0
  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.0.10+1
  # https://pub.dev/packages/collection
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.5.0+1
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  flutter_gen: ^5.5.0+1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: LexendMega
      fonts:
        - asset: assets/fonts/LexendMega-Regular.ttf
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500


flutter_intl:
  enabled: true

flutter_gen:
  output: lib/generated/assets

flutter_native_splash:
  android: true
  ios: true
  web: false
  image: "assets/images/splash_screen/splash_screen.png"
  color: "#2E6653"
  android_12:
    color: "#2E6653"
    image: "assets/images/splash_screen/splash_screen_12+.png"